import React from 'react';
import { Database, Key, CheckCircle, AlertTriangle, FileCode, ArrowRight } from 'lucide-react';
import { AppConfig } from '../types';

interface ConfigGuideProps {
  config: AppConfig;
  supabaseConnected: boolean;
  onRefresh: () => void;
}

export default function ConfigGuide({ config, supabaseConnected, onRefresh }: ConfigGuideProps) {
  const ddlQuery = `-- 1. PROFILES TABLE
CREATE TABLE profiles (
  id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email text NOT NULL UNIQUE,
  display_name text,
  role text NOT NULL DEFAULT 'staff' CHECK (role IN ('staff', 'admin')),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 2. CUSTOMERS TABLE
CREATE TABLE customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (name ~ '^[A-Za-z \\u00C0-\\u017F]{2,40}$'),
  phone text NOT NULL UNIQUE CHECK (phone ~ '^[6-9]\\d{9}$'),
  delivery_address text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 3. MENU ITEMS TABLE
CREATE TABLE menu_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  category text NOT NULL CHECK (category IN ('base', 'pizza', 'topping')),
  name text NOT NULL,
  price_inr numeric(10,2) NOT NULL CHECK (price_inr > 0),
  currency text NOT NULL DEFAULT 'INR',
  description text,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 4. ORDERS TABLE
CREATE TABLE orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint REFERENCES customers(id) ON DELETE SET NULL NULL,
  customer_name text NOT NULL CHECK (customer_name ~ '^[A-Za-z \\u00C0-\\u017F]{2,40}$'),
  customer_phone text NOT NULL CHECK (customer_phone ~ '^[6-9]\\d{9}$'),
  table_number integer NOT NULL CHECK (table_number BETWEEN 1 AND 20),
  total_quantity integer NOT NULL CHECK (total_quantity BETWEEN 1 AND 10),
  subtotal numeric(10,2) NOT NULL CHECK (subtotal >= 0),
  discount numeric(10,2) NOT NULL DEFAULT 0 CHECK (discount >= 0), 
  gst numeric(10,2) NOT NULL CHECK (gst >= 0), 
  total_payable numeric(10,2) NOT NULL CHECK (total_payable >= 0),
  currency text NOT NULL DEFAULT 'INR',
  payment_mode text NOT NULL CHECK (payment_mode IN ('Cash', 'Card', 'UPI')),
  order_source text NOT NULL DEFAULT 'staff' CHECK (order_source IN ('staff', 'customer')),
  status text NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed', 'preparing', 'ready', 'delivered', 'cancelled')),
  staff_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  session_started_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  cooking_started_at timestamptz,
  ready_at timestamptz,
  delivered_at timestamptz,
  cancelled_at timestamptz,
  cancellation_reason text
);

-- 5. ORDER ITEMS TABLE
CREATE TABLE order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
  menu_item_id bigint REFERENCES menu_items(id) ON DELETE SET NULL,
  category text NOT NULL,
  name text NOT NULL,
  unit_price_snapshot numeric(10,2) NOT NULL CHECK (unit_price_snapshot >= 0),
  currency text NOT NULL DEFAULT 'INR',
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);`;

  return (
    <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm space-y-6" id="config-guide">
      <div className="border-b border-gray-100 pb-3 flex justify-between items-center">
        <div>
          <h3 className="font-bold text-gray-800 text-base flex items-center gap-1.5">
            <Database className="w-5 h-5 text-red-600" /> Environment Keys & Supabase Diagnostics
          </h3>
          <p className="text-xs text-gray-500 mt-1">Review connection parameters and run SQL initializations.</p>
        </div>
        <button
          onClick={onRefresh}
          className="px-3 py-1 bg-gray-50 border border-gray-200 hover:bg-gray-100 rounded-lg text-xs font-semibold cursor-pointer text-gray-600"
        >
          Re-Check Connection
        </button>
      </div>

      {/* Grid status keys */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Supabase connection status card */}
        <div className={`p-4 rounded-xl border flex items-start space-x-3 ${
          supabaseConnected ? 'bg-emerald-50/50 border-emerald-200 text-emerald-800' : 'bg-amber-50/50 border-amber-200 text-amber-800'
        }`}>
          <div className={`p-2 rounded-lg ${supabaseConnected ? 'bg-emerald-100' : 'bg-amber-100'}`}>
            <Database className="w-5 h-5" />
          </div>
          <div>
            <h4 className="font-bold text-xs">Supabase Storage Link</h4>
            <p className="text-[10px] mt-0.5 leading-snug">
              {supabaseConnected 
                ? 'Linked successfully! Executing active queries on live Postgres tables.' 
                : 'Using Local Storage Fallback mode. Fully functional for sandbox testing.'}
            </p>
          </div>
        </div>

        {/* Supabase env variables key card */}
        <div className={`p-4 rounded-xl border flex items-start space-x-3 ${
          config.supabaseUrl && config.supabaseAnonKey ? 'bg-emerald-50/50 border-emerald-200 text-emerald-800' : 'bg-amber-50/50 border-amber-200 text-amber-800'
        }`}>
          <div className={`p-2 rounded-lg ${config.supabaseUrl && config.supabaseAnonKey ? 'bg-emerald-100' : 'bg-amber-100'}`}>
            <Key className="w-5 h-5" />
          </div>
          <div>
            <h4 className="font-bold text-xs">Supabase Environment Keys</h4>
            <p className="text-[10px] mt-0.5 leading-snug font-mono break-all">
              {config.supabaseUrl ? `URL: ${config.supabaseUrl.slice(0, 24)}...` : 'SUPABASE_URL is missing'}
              <br />
              {config.supabaseAnonKey ? `Key: ${config.supabaseAnonKey.slice(0, 24)}...` : 'SUPABASE_ANON_KEY is missing'}
            </p>
          </div>
        </div>

        {/* Gemini variables key card */}
        <div className={`p-4 rounded-xl border flex items-start space-x-3 ${
          config.hasGemini ? 'bg-emerald-50/50 border-emerald-200 text-emerald-800' : 'bg-amber-50/50 border-amber-200 text-amber-800'
        }`}>
          <div className={`p-2 rounded-lg ${config.hasGemini ? 'bg-emerald-100' : 'bg-amber-100'}`}>
            <Key className="w-5 h-5" />
          </div>
          <div>
            <h4 className="font-bold text-xs">Gemini AI Key</h4>
            <p className="text-[10px] mt-0.5 leading-snug">
              {config.hasGemini 
                ? 'GEMINI_API_KEY is active! Chatbot can resolve billing, pricing and status queries.' 
                : 'GEMINI_API_KEY is missing. Chatbot will show helper instructions.'}
            </p>
          </div>
        </div>
      </div>

      {/* Guide how to link */}
      <div className="space-y-4 pt-2">
        <h4 className="font-bold text-gray-800 text-xs uppercase tracking-wider text-gray-400">Step-by-step Setup Guide</h4>

        <div className="space-y-3.5 text-xs text-gray-600">
          <div className="flex items-start gap-2.5">
            <span className="w-5 h-5 rounded-full bg-red-100 text-red-600 font-bold flex items-center justify-center text-[10px] flex-shrink-0">1</span>
            <div>
              <p className="font-bold text-gray-800">Add Secrets in AI Studio</p>
              <p className="mt-0.5">Open the **Settings &gt; Secrets** panel in the bottom-left of Google AI Studio. Add `SUPABASE_URL`, `SUPABASE_ANON_KEY`, and `GEMINI_API_KEY` to link your production environment securely.</p>
            </div>
          </div>

          <div className="flex items-start gap-2.5">
            <span className="w-5 h-5 rounded-full bg-red-100 text-red-600 font-bold flex items-center justify-center text-[10px] flex-shrink-0">2</span>
            <div>
              <p className="font-bold text-gray-800">Run SQL Queries in Supabase</p>
              <p className="mt-0.5">Open your project in the **Supabase Dashboard**, navigate to the **SQL Editor**, and execute the DDL table commands below to create the necessary tables:</p>
              
              <div className="mt-3 bg-gray-900 text-gray-100 p-4 rounded-xl font-mono text-[10px] max-h-[160px] overflow-y-auto whitespace-pre">
                {ddlQuery}
              </div>
            </div>
          </div>

          <div className="flex items-start gap-2.5">
            <span className="w-5 h-5 rounded-full bg-red-100 text-red-600 font-bold flex items-center justify-center text-[10px] flex-shrink-0">3</span>
            <div>
              <p className="font-bold text-gray-800">Seed Default Catalog</p>
              <p className="mt-0.5">Once tables are created and keys are connected, click the **"Seed Supabase Tables"** button in the Executive tab. This will populate your SQL database with our master pizza list, crusts, and toppings automatically!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
